name: Android APK Build

on:
  push:
    branches:
      - main
      - test-build

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Grant Execute Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Clean and Build Debug APK
        run: ./gradlew clean assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParkNJoy-APK
          path: app/build/outputs/apk/debug/app-debug.apk
